type Permissions = {
  VIEW?: string
  CREATE?: string
  UPDATE?: string
  DELETE?: string
  BLOCK?: string
  AUTHORIZE?: string
}

type APPPermissionsType = {
  ADMIN: string
  DASHBOARD: Permissions
  COURSES: Permissions & {
    REVIEW: string
  }
  STUDENT: Permissions
  PRIVATE_USER: Permissions
  INSTRUCTORS: Permissions
  USER: Permissions
  ROLE: Permissions
  CATEGORY: Permissions
}

// Define your permissions object with proper typing
export const APP_PERMISSIONS: APPPermissionsType = {
  ADMIN: 'ADMIN_APP',
  DASHBOARD: {
    VIEW: 'DASHBOARD.VIEW'
  },
  STUDENT: {
    CREATE: 'STUDENT.CREATE',
    UPDATE: 'STUDENT.UPDATE',
    VIEW: 'STUDENT.VIEW',
    DELETE: 'STUDENT.DELETE'
  },
  PRIVATE_USER: {
    CREATE: 'PRIVATE_USER.CREATE',
    UPDATE: 'PRIVATE_USER.EDIT',
    VIEW: 'PRIVATE_USER.VIEW',
    DELETE: 'PRIVATE_USER.DELETE',
    BLOCK: 'PRIVATE_USER.BLOCK',
    AUTHORIZE: 'PRIVATE_USER.AUTHORIZE'
  },
  ROLE: {
    CREATE: 'ROLE.CREATE',
    UPDATE: 'ROLE.EDIT',
    VIEW: 'ROLE.VIEW',
    DELETE: 'ROLE.DELETE'
  },
  USER: {
    CREATE: 'USER.CREATE',
    UPDATE: 'USER.EDIT',
    VIEW: 'USER.VIEW',
    DELETE: 'USER.DELETE',
    BLOCK: 'USER.BLOCK'
  },
  INSTRUCTORS: {
    CREATE: 'INSTRUCTORS.CREATE',
    UPDATE: 'INSTRUCTORS.UPDATE',
    VIEW: 'INSTRUCTORS.VIEW',
    DELETE: 'INSTRUCTORS.DELETE'
  },
  COURSES: {
    VIEW: 'COURSE.VIEW',
    CREATE: 'COURSE.CREATE',
    UPDATE: 'COURSE.UPDATE',
    DELETE: 'COURSE.DELETE',
    REVIEW: 'COURSE.REVIEW'
  },
  CATEGORY: {
    VIEW: 'CATEGORY.VIEW',
    CREATE: 'CATEGORY.CREATE',
    UPDATE: 'CATEGORY.UPDATE',
    DELETE: 'CATEGORY.DELETE'
  }
}
